FROM nginx:1.27

RUN mkdir /etc/nginx/ssl

COPY ./GoltStars/reverse_proxy/nginx/conf/local.conf /etc/nginx/conf.d/default.conf

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/selfsigned.key -out /etc/nginx/ssl/selfsigned.crt -subj "/C=FR/ST=GoltStars/L=Paris/O=ESIEE-IT/OU=FR/CN=localhost"

EXPOSE 80