FROM node:20-alpine

ENV APP_DIR=/app
ENV TZ=Europe/Paris

WORKDIR ${APP_DIR}/GoltStars/front_end
COPY ./GoltStars/front_end/package.json .
RUN npm install

COPY ./GoltStars/front_end/ .
CMD ["npm", "run", "dev", "--", "--host"]
