FROM php:8.2-fpm

# Variables d'environnement
ENV APP_DIR /var/www/html
ENV TZ=Europe/Paris

EXPOSE 9000

## Installation des extensions pour Symfony
RUN apt-get update && apt-get install -y \
    zip git openssl libicu-dev libpq-dev libaio1 \
    locales curl wget tar unzip && \
    docker-php-ext-install intl pdo pdo_mysql

WORKDIR ${APP_DIR}/GoltStars/back_end

## Installation de Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

## On télécharge le binaire de Symfony CLI puis on le déplace de son emplacement temporaire dans le conteneur vers '/usr/local/bin/symfony'
## Enfin, on supprime le dossier temporaire '/root/.symfony*'
RUN curl -sS https://get.symfony.com/cli/installer | bash && \
    mv /root/.symfony*/bin/symfony /usr/local/bin/symfony && \
    rm -rf /root/.symfony*

## Copie du fichier composer.json du projet pour installer la liste des dépendances nécessaires avec la commande composer install
COPY ./GoltStars/back_end/composer.json .

RUN composer install

## Copie du projet symfony dans '/var/www/html/GoltStars/back_end'
COPY ./GoltStars/back_end .

## Permet d'installer et de configurer les dépendances JavaScript
#RUN php bin/console importmap:install

## Supprime le cache de symfony
RUN php bin/console cache:clear

## Génération du certificat TLS local afin de pouvoir se connecter en HTTPS
RUN symfony server:ca:install

## Lance PHP-FPM
CMD ["php-fpm"]

## Ci-dessous, commande pour lancer un conteneur et le laisser actif
#CMD ["tail", "-f", "/dev/null"]